### PR TITLE
nutsack

### PR DESCRIPTION
**Pull request by nruff9**

### CODE REVIEW

**Comment by MattyB03** [comment]
I like this

**Comment by DanielW3** [comment]
I like them

**Comment by DanielW3** [comment]
Hot ;)

**Comment by Ethecheese** [comment]
REEEEEEEEEEEEEEEEEEEEEEE IMMMMMM TRRRRRRRRRIIIIIIIGGGGGGGGGEEEEERRRRRRRREEEEDDDDDD

**Pull request merged**
